name: QA-A PR Checks

on:
  pull_request:

jobs:

  robot-dry-run:
    name: Robot Dry Run
    runs-on: ubuntu-latest

    steps:
      - name: Get repository code
        uses: actions/checkout@v4

      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run Robot Framework dry run
        run: robot --dryrun tests/


  robocop:
    name: QA-A Code Quality
    runs-on: ubuntu-latest

    steps:
      - name: Get repository code
        uses: actions/checkout@v4

      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run Robocop
        run: robocop check tests/